"""Parsing and detokenization for MultiCoNER dataset files."""

import re
from collections.abc import Iterable, Iterator
from dataclasses import dataclass
from typing import Literal

import httpx
from defusedxml import ElementTree as ETree


@dataclass
class Token:
    """Token with BIO-format entity annotation."""

    text: str
    type: Literal["outside", "beginning", "inside"]
    label: str


@dataclass
class Entity:
    """Sequence of tokens forming a named entity."""

    tokens: list[Token]
    label: str

    def detokenize(self, lang: str):
        """Reconstruct original entity text using language-specific spacing rules."""
        return detokenize(lang, [x.text for x in self.tokens])


@dataclass
class Utterance:
    """Complete utterance with annotated entities."""

    id: str
    domain: str
    tokens: list[Token]
    entities: list[Entity]

    def detokenize(self):
        """Reconstruct original text using language-specific spacing rules."""
        return detokenize(self.domain, [x.text for x in self.tokens])


def stream_conll_lines(bucket: str, prefix: str) -> Iterator[str]:
    """
    Walks down the given bucket/prefix and streams all the lines of all the
    .conll files as a stream.

    Notes
    -----
    We're rolling this without a S3 client because the whole thing is
    unauthenticated and there is no point loading gigatons of boto3 if we can
    just have 20 lines of code.

    Parameters
    ----------
    bucket
        Name of the S3 bucket to walk
    prefix
        Prefix within which to search
    """

    list_url = f"https://{bucket}.s3.amazonaws.com/?list-type=2&prefix={prefix}"

    continuation_token = None
    while True:
        url = list_url
        if continuation_token:
            url += f"&continuation-token={continuation_token}"

        response = httpx.get(url)
        root = ETree.fromstring(response.content)

        # Parse XML namespace
        ns = {"s3": "http://s3.amazonaws.com/doc/2006-03-01/"}

        # Stream each .conll file
        for obj in root.findall("s3:Contents", ns):
            key_elem = obj.find("s3:Key", ns)
            if key_elem is None or key_elem.text is None:
                continue
            key = key_elem.text

            if not key.endswith(".conll"):
                continue

            # Stream file line by line
            file_url = f"https://{bucket}.s3.amazonaws.com/{key}"
            with httpx.stream("GET", file_url) as r:
                yield from r.iter_lines()

        # Check if there are more pages
        is_truncated = root.find("s3:IsTruncated", ns)
        if is_truncated is None or is_truncated.text == "false":
            break

        continuation_token_elem = root.find("s3:NextContinuationToken", ns)
        if continuation_token_elem is None or continuation_token_elem.text is None:
            break
        continuation_token = continuation_token_elem.text


header_pattern = r"^#\s+id\s+(?P<id>[a-f0-9-]+)\s+domain=(?P<domain>\w+)"
word_o_pattern = r"^(?P<token>\S+)\s+_\s+_\s+O$"
entity_start_pattern = r"^(?P<token>\S+)\s+_\s+_\s+B-(?P<entity_type>\S+)$"
entity_continuation_pattern = r"^(?P<token>\S+)\s+_\s+_\s+I-(?P<entity_type>\S+)$"


def parse_conll(lines: Iterable[str]) -> Iterator[Utterance]:  # noqa: C901
    """
    Parsing the provided .conll file, line by line. Essentially it's expected
    to be a stream of lines, as generated by stream_conll_lines(), but can
    also be a regular open file.

    Parameters
    ----------
    lines
        Stream of lines to parse
    """

    utterance: Utterance | None = None
    entity: Entity | None = None

    def flush_utterance():
        nonlocal utterance

        flush_entity()

        if utterance is not None:
            yield utterance
            utterance = None

    def flush_entity():
        nonlocal entity

        if entity is not None and utterance is not None:
            utterance.entities.append(entity)
            entity = None

    for line in lines:
        if m := re.match(header_pattern, line):
            yield from flush_utterance()
            utterance = Utterance(m.group("id"), m.group("domain"), [], [])
        elif (m := re.match(word_o_pattern, line)) and utterance is not None:
            flush_entity()
            token = Token(m.group("token"), "outside", "")
            utterance.tokens.append(token)
        elif (m := re.match(entity_start_pattern, line)) and utterance is not None:
            flush_entity()
            token = Token(m.group("token"), "beginning", m.group("entity_type"))
            entity = Entity([token], token.label)
            utterance.tokens.append(token)
        elif (
            (m := re.match(entity_continuation_pattern, line))
            and entity is not None
            and utterance is not None
        ):
            token = Token(m.group("token"), "inside", m.group("entity_type"))
            entity.tokens.append(token)
            utterance.tokens.append(token)
        elif not line:
            yield from flush_utterance()

    yield from flush_utterance()


def detokenize(lang_code: str, tokens: list[str]) -> str:
    """
    Detokenize a sequence of tokens based on language-specific rules.

    Supports MultiCoNER 2023 languages with heuristic-based spacing rules.
    Works for European, Indic, Chinese, and Farsi tokenization conventions.

    Parameters
    ----------
    lang_code : str
        Two-letter ISO 639-1 language code (lowercase).
        Supported: 'en', 'es', 'pt', 'fr', 'de', 'it', 'sv', 'uk',
                   'hi', 'bn', 'zh', 'fa', 'multi'.
    tokens : list[str]
        List of tokenized strings to join into a sentence.

    Returns
    -------
    str
        Detokenized text with appropriate spacing for the given language.

    Examples
    --------
    >>> tokens = ["Hello", ",", "world", "!"]
    >>> detokenize("en", tokens)
    'Hello, world!'

    >>> tokens = ["বেল", "ল্যাবস্", "।"]
    >>> detokenize("bn", tokens)
    'বেল ল্যাবস্।'

    >>> tokens = ["你好", "world", "！"]
    >>> detokenize("zh", tokens)
    '你好 world！'

    Notes
    -----
    This implementation uses heuristics and may not perfectly match the
    original tokenization scheme. For production use, consider using
    language-specific detokenizers like Moses or IndicNLP.

    Chinese (zh) joins characters without spaces except around Latin text.
    RTL languages (fa) are returned in logical order (not visual order).
    """
    if not tokens:
        return ""

    lang = lang_code.lower()

    # Dispatch to language-specific handlers
    if lang == "zh":
        return _detokenize_chinese(tokens)
    elif lang in ["hi", "bn"]:
        return _detokenize_indic(tokens)
    elif lang == "fa":
        return _detokenize_farsi(tokens)
    else:
        # Default: European languages (en, es, pt, fr, de, it, sv, uk, multi)
        return _detokenize_european(tokens)


def _detokenize_european(tokens: list[str]) -> str:
    """
    Detokenize European languages.

    Parameters
    ----------
    tokens : list[str]
        Tokenized words and punctuation.

    Returns
    -------
    str
        Detokenized text.
    """
    result = []

    for i, token in enumerate(tokens):
        if i == 0:
            result.append(token)
            continue

        prev_token = tokens[i - 1]

        # No space before these punctuation marks
        if token in [
            ".",
            ",",
            "!",
            "?",
            ":",
            ";",
            ")",
            "]",
            "}",
            "%",
            "…",
            "...",
            "'s",
            "n't",
            "'re",
            "'ve",
            "'ll",
            "'d",
            "'m",
        ]:
            result.append(token)

        # No space after these
        elif prev_token in ["(", "[", "{", "$", "€", "£", "¥", "#", "@", "¿", "¡"]:
            result.append(token)

        # Handle quotes and apostrophes
        elif token in ['"', "'"] and prev_token in [".", ",", "!", "?", ";"]:
            result.append(token)

        # Hyphens: no space if between word parts
        elif token == "-" or prev_token == "-":  # noqa: S105
            result.append(token)

        # Slashes in dates, URLs
        elif token == "/" or prev_token == "/":  # noqa: S105
            result.append(token)

        # Default: add space
        else:
            result.append(" " + token)

    return "".join(result)


def _detokenize_chinese(tokens: list[str]) -> str:
    """
    Detokenize Chinese text.

    Parameters
    ----------
    tokens : list[str]
        Tokenized Chinese characters and words.

    Returns
    -------
    str
        Detokenized text with no spaces except around Latin script.
    """
    result = []

    for i, token in enumerate(tokens):
        if i == 0:
            result.append(token)
            continue

        prev_token = tokens[i - 1]

        # Add space when mixing scripts (CJK <-> Latin)
        if _is_latin(token) and not _is_latin(prev_token):
            result.append(" " + token)
        elif _is_latin(prev_token) and not _is_latin(token):
            result.append(" " + token)
        # No space before CJK punctuation
        elif token in [
            "，",
            "。",
            "！",
            "？",
            "：",
            "；",
            "、",
            "）",
            "】",
            "》",
            "」",
            "』",
        ]:
            result.append(token)
        # No space after CJK opening punctuation
        elif prev_token in [
            "（",
            "【",
            "《",
            "「",
            "『",
        ]:
            result.append(token)
        # Latin-Latin: add space
        elif _is_latin(token) and _is_latin(prev_token):
            result.append(" " + token)
        # Default: no space (CJK-CJK)
        else:
            result.append(token)

    return "".join(result)


def _detokenize_indic(tokens: list[str]) -> str:
    """
    Detokenize Indic languages (Hindi, Bengali).

    Parameters
    ----------
    tokens : list[str]
        Tokenized Indic script words and punctuation.

    Returns
    -------
    str
        Detokenized text with appropriate spacing.
    """
    result = []

    for i, token in enumerate(tokens):
        if i == 0:
            result.append(token)
            continue

        prev_token = tokens[i - 1]

        # No space before Indic and Latin punctuation
        if token in ["।", "॥", "?", "!", ",", ".", ":", ";", ")", "]", "}", "%"]:
            result.append(token)

        # No space after opening brackets
        elif prev_token in ["(", "[", "{"]:
            result.append(token)

        # Hyphenated compounds (no space)
        elif token == "-" or prev_token == "-":  # noqa: S105
            result.append(token)

        # Default: add space
        else:
            result.append(" " + token)

    return "".join(result)


def _detokenize_farsi(tokens: list[str]) -> str:
    """
    Detokenize Farsi/Persian text.

    Parameters
    ----------
    tokens : list[str]
        Tokenized Farsi words and punctuation.

    Returns
    -------
    str
        Detokenized text with appropriate spacing (logical order).
    """
    result = []

    for i, token in enumerate(tokens):
        if i == 0:
            result.append(token)
            continue

        prev_token = tokens[i - 1]

        # No space before Persian punctuation
        if token in ["،", "؛", "؟", "!", ".", ":", ")", "]", "}", "%"]:
            result.append(token)

        # No space after opening brackets
        elif prev_token in ["(", "[", "{"]:
            result.append(token)

        # Zero-width non-joiner (ZWNJ) - no spaces
        elif token in ["\u200c", "\u200d"]:
            result.append(token)
        elif prev_token in ["\u200c", "\u200d"]:
            result.append(token)

        # Hyphenated compounds
        elif token == "-" or prev_token == "-":  # noqa: S105
            result.append(token)

        # Default: add space
        else:
            result.append(" " + token)

    return "".join(result)


def _is_latin(text: str) -> bool:
    """
    Check if text contains Latin script characters.

    Parameters
    ----------
    text : str
        Text to check.

    Returns
    -------
    bool
        True if text contains any Latin (ASCII) letters.
    """
    if not text:
        return False
    return any(("\u0041" <= c <= "\u005a") or ("\u0061" <= c <= "\u007a") for c in text)
